# Generated by Django 6.0.6 on 2026-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('full_meal', 'Full meal'), ('snack', 'Snack'), ('desert', 'Desert')], default='full_meal', max_length=15),
        ),
    ]
