# Generated by Django 6.0.6 on 2026-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplink',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
