# Generated by Django 6.0.6 on 2026-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_saved_grocery_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgrocerylist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
