# Generated by Django 6.0.6 on 2026-07-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_archive_grocery_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisle',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_aisles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisleorder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisleorder',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_aisle_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryaislemapping',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryaislemapping',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_category_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_ingredients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_recipe_ingredients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedgroceryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedgroceryitem',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_grocery_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedgrocerylist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedgrocerylist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_grocery_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoplink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoplink',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_shop_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoplocation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoplocation',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_shop_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
